variables:
  CONTAINER_IMAGE: "gitlab.inf.unibz.it:4567/lter/browser"
  DOCKER_TESTER_IMAGE: "golang:1.13.5"
  DOCKER_BUILDER_IMAGE: "docker:19.03.1"
  DOCKER_TLS_CERTDIR: "" # See https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
  KUBECTL: "https://storage.googleapis.com/kubernetes-release/release/v1.8.10/bin/linux/amd64/kubectl"

stages:
  - testing
  - build
  - tag
  - deploy

testing:
  stage: testing
  tags:
    - shared
  image: ${DOCKER_TESTER_IMAGE}
  script:
    - export GONOPROXY="gitlab.inf.unibz.it"
    - export GONOSUMDB="gitlab.inf.unibz.it"
    - go get honnef.co/go/tools/cmd/staticcheck
    - go env
    - cd ${CI_PROJECT_DIR}
    - diff -u <(echo -n) <(gofmt -d -s .)
    - go vet ./...
    - go test -v -race ./...
    - staticcheck ./...
  only:
    - master
    - merge_requests

build:
  stage: build
  tags:
    - dind
  image: ${DOCKER_BUILDER_IMAGE}
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN https://gitlab.inf.unibz.it:4567
  script:
    - docker build --rm --no-cache --tag=${CONTAINER_IMAGE}:${CI_COMMIT_SHA} .
    - docker push ${CONTAINER_IMAGE}:${CI_COMMIT_SHA}
    - docker tag ${CONTAINER_IMAGE}:${CI_COMMIT_SHA} ${CONTAINER_IMAGE}:staging
    - docker push ${CONTAINER_IMAGE}:staging
  only:
   - master

deploy_staging:
  stage: deploy
  tags:
    - dind
  image: ${DOCKER_BUILDER_IMAGE}
  services:
    - docker:dind
  before_script:
    - wget ${KUBECTL}
    - mv kubectl /usr/bin/
    - chmod +x /usr/bin/kubectl
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.inf.unibz.it:4567
  script:
    - docker pull ${CONTAINER_IMAGE}:${CI_COMMIT_SHA}
    - kubectl --namespace eurac-alpenv-browser-stage set image deployment/browser browser=${CONTAINER_IMAGE}:${CI_COMMIT_SHA}
  environment:
    name: staging
    url: https://browser-stage.lter.eurac.edu
  only:
    - master

deploy_production:
  stage: deploy
  tags:
    - dind
  image: ${DOCKER_BUILDER_IMAGE}
  services:
    - docker:dind
  before_script:
    - wget ${KUBECTL}
    - mv kubectl /usr/bin/
    - chmod +x /usr/bin/kubectl
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.inf.unibz.it:4567
  script:
    - docker pull ${CONTAINER_IMAGE}:${CI_COMMIT_SHA}
    - docker tag ${CONTAINER_IMAGE}:${CI_COMMIT_SHA} ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
    - docker tag ${CONTAINER_IMAGE}:${CI_COMMIT_SHA} ${CONTAINER_IMAGE}:latest
    - docker push ${CONTAINER_IMAGE}:latest
    - kubectl config set-credentials gitlab-deploy --token=$K8S_PRODUCTION_TOKEN
    - kubectl --namespace eurac-alpenv set image deployment/browser browser=${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
  environment:
    name: production
    url: https://browser.lter.eurac.edu
  only:
    - tags
